name: Linux.

on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'

jobs:
    create_release:
        name: Create_Release
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4
    
          - name: Setup Go 1.21.x
            uses: actions/setup-go@v4
            with:
                go-version: '1.21.x'
            
          - name: Installing sqlite3
            run: | 
              sudo apt-get update
              sudo apt-get install --yes sqlite3 
          
          - name: Creating a database file.
            run: make makedb

          - name: Build App
            run: make build

          - name: Create directory
            run: |
              mkdir reminders_tg_bot_linux_x64
              cp remindersTgBot.db reminders_tg_bot_linux_x64/
              cp config.json reminders_tg_bot_linux_x64/
              cp LICENSE reminders_tg_bot_linux_x64/
              cp README.md reminders_tg_bot_linux_x64/
              cp reminders_tg_bot reminders_tg_bot_linux_x64/
              tar -czvf reminders_tg_bot_linux_x64.tar.gz reminders_tg_bot_linux_x64
            working-directory: ${{ github.workspace }}

          - name: Create GitHub Release
            id: create_release
            uses: softprops/action-gh-release@v1
            with:
              files: reminders_tg_bot_linux_x64.tar.gz
              tag_name: latest
            env:
              GITHUB_TOKEN: ${{ secrets.ACTIONS }}